### PR TITLE
CI: also run branch against python 2.7

### PR DESCRIPTION
**Pull request by CJ-Wright**
I'm curious to see if py3k is backward compatable.

### CODE REVIEW

**Comment by pavoljuhas** [comment]
Nope - I have opted to make python3 branch py3-only 12f19cce115dca4242a6baab6a4c81d7a9928aa9.  No need to worry about py2 compatibility.  We can cherry-pick fixes that are suitable for Python 2 (master) branch.

Also, conda recipe is [disabled for Python 2](https://github.com/diffpy/diffpy.srfit/blob/python3/conda-recipe/meta.yaml#L10).

**Comment by CJ-Wright** [comment]
Why was this decision made? How many of the python 3 changes are incompatible with python 2?

**Comment by pavoljuhas** [comment]
> Why was this decision made?

To take full advantage of Python 3 without getting bogged down writing PY2 compatible code.

I plan major refactoring of diffpy.structure which is introducing incompatible changes.  It is IMHO a good opportunity to break off Python 2.

**Comment by CJ-Wright** [comment]
Hmm, ok.
One option is to run the CI against python 2 and use the `allow_failures` flag to allow the python 2k builds to fail without failing the PR. This way if we by chance don't use some of the awesome py3k features (`*` everywhere) we can still know that we support py2k tacitly.
Do you mind putting your refactor in as a PR? (I'm getting a bit of whiplash from the direct pushes)

**Comment by pavoljuhas** [comment]
> Do you mind putting your refactor in as a PR? (I'm getting a bit of whiplash from the direct pushes)

You mean future refactors?  Yes, I can do so to have more of record keeping for the project.

Is there a problem with direct pushes of obvious changes?

**Comment by CJ-Wright** [comment]
Usually direct pushes are avoided. That way people can see what the changes are before they go in. It also gives the CI time to check if the changes break anything and to make certain that test coverage is preserved or increased. Many projects now have protected master branches to prevent direct pushing. Part of this is cultural, most of the major scientific stack (and many other projects) discourage direct pushes.

More concretely, this workflow would have most likely prevented your revert commit from the other day as the CI on the PR would have shown the error before it made it into master. IMHO every merge should leave the repo in a "release quality" state, users could install from source and be greeted by code that works and PRs help prevent buggy code from making it into master.

**Comment by CJ-Wright** [comment]
This might be a good example workflow, we don't have to implement all of it.
https://github.com/cyclus/cyclus/blob/develop/CONTRIBUTING.rst

**Pull request closed without merging**
