### PR TITLE
TST/CI: cover the tests

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by pavoljuhas** [comment]
@CJ-Wright - what exactly do we get by adding the .codecov.yml file?

**Comment by CJ-Wright** [comment]
Now the codecov report includes the coverage for the tests (88.3%)

**Comment by pavoljuhas** [comment]
Please rebase this of master@55fd876c350c66de93a6ee40f879f2bb3f7bb368 and squash to a single commit.  Also add newline to the end of .codecov.yml.

**Comment by CJ-Wright** [comment]
Why do I need to rebase? (there are no merge conficts)

**Comment by CJ-Wright** [comment]
See #29

**Comment by pavoljuhas** [comment]
To keep project history simple - why should we add 5 commits that in effect add one file?

Also a merge of this PR would span over sources move to the `src/` directory making the diff vs first and second parent confusing.

**Comment by CJ-Wright** [comment]
I didn't have a problem with the squash.

Are you using a delineated workflow for the project?
If not might I suggest the [numpy workflow](https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html)?
I think this could have helped with these kinds of issues.

**Comment by pavoljuhas** [comment]
It's more rule of the thumb - if a feature is fairly simple or has dummy/reverted commits and is easy to rebase - rebase, otherwise merge.  Also, please pull from the upstream repo before starting a new feature branch.

**Pull request closed without merging**
