### PR TITLE
Remove conda recipe files

### PR DESCRIPTION
**Pull request by bobleesj**
Conda recipe files are moved in the current repo since they are managed in a separate folder:

https://github.com/conda-forge/staged-recipes/pull/25665

### CODE REVIEW

**Review by sbillinge — COMMENTED** [review]
before we delete these, are we sure that we have the `meta.yaml` information all saved somewhere (e.g., in `release-scripts` or the cf feedstock, so we don't lose useful information?  Once confrmed I iwll merge this.

**Comment by bobleesj** [comment]
I noticed that the `meta.yml` file in the diffpy.srfit conda-forge recipe under review is different from what is provided here: https://github.com/conda-forge/staged-recipes/pull/25665. So no merge at the moment.. (yet)

Seems like we already have `diffpy.srfit` conda package available here: https://anaconda.org/diffpy/diffpy.srfit, but it's not via the conda-forge channel.

Shall we wait to delete these files once we have `diffpy.srfit` available on conda-forge? @sbillinge

**Comment by sbillinge** [comment]
> I noticed that the `meta.yml` file in the diffpy.srfit conda-forge recipe under review is different from what is provided here: [conda-forge/staged-recipes#25665](https://github.com/conda-forge/staged-recipes/pull/25665). So no merge at the moment.. (yet)
> 
> Seems like we already have `diffpy.srfit` conda package available here: https://anaconda.org/diffpy/diffpy.srfit, but it's not via the conda-forge channel.
> 
> Shall we wait to delete these files once we have `diffpy.srfit` available on conda-forge? @sbillinge

yes.  Let's capture that in an issue so we remember to revisit....

**Comment by bobleesj** [comment]
> > I noticed that the `meta.yml` file in the diffpy.srfit conda-forge recipe under review is different from what is provided here: [conda-forge/staged-recipes#25665](https://github.com/conda-forge/staged-recipes/pull/25665). So no merge at the moment.. (yet)
> > Seems like we already have `diffpy.srfit` conda package available here: https://anaconda.org/diffpy/diffpy.srfit, but it's not via the conda-forge channel.
> > Shall we wait to delete these files once we have `diffpy.srfit` available on conda-forge? @sbillinge
> 
> yes. Let's capture that in an issue so we remember to revisit....

https://github.com/diffpy/diffpy.srfit/issues/86

Yes

**Comment by bobleesj** [comment]
Will re-open once we have diffpy.srfit feedstock

**Pull request closed without merging**
