### PR TITLE
Wrapped dictionary .values() call in list

### LINKED ISSUE #60: Python 3 compatibility with dictionary views vs lists.
So, if I try to run a co-refinement, where I have more than one fit contribution, generally the recipe building goes fine.

But, I if call something like `FitResults(recipe).printResults()` I get:

```
...
AttributeError: 'odict_keys' object has no attribute 'sort'

```

Something similar occurs if I call `recipe.setWeights`

I think this is because dictionary keys/values etc are being treated as lists (python 2)

I'll see if I can fix it.

### PR DESCRIPTION
**Pull request by rjkoch**
Closes #60, dict.values() does not return list. WIP.

### CODE REVIEW

**Comment by rjkoch** [comment]
ready for review

**Comment by rjkoch** [comment]
Has there been any progress on accepting this? The current version does not support writing results from multi-profile recipe, which is problematic

**Comment by sbillinge** [comment]
Pavol is pretty much awol atm.  I will take a look and see if I feel
comfortable enough to merge it, though normally I would want to hear from
Pavol.  This may change moving forward :(

**Comment by rjkoch** [comment]
Alright, fair enough.

**Comment by pavoljuhas** [comment]
Looks good to me.

**Pull request merged**
