### PR TITLE
Cookiecuting - git add untracked files

### PR DESCRIPTION
**Pull request by bobleesj**
Here, adding untracked files with cookiecutting.

In a separate PR, I will address the following files:

```
	modified:   .codecov.yml
	modified:   .coveragerc
	modified:   .flake8
	deleted:    .gitarchive.cfg
	modified:   .gitattributes
	modified:   .gitignore
	deleted:    .idea/.gitignore
	modified:   .pre-commit-config.yaml
	deleted:    .travis.yml
	deleted:    AUTHORS.txt
	deleted:    CHANGELOG.md
	deleted:    LICENSE.txt
	deleted:    LICENSE_DANSE.txt
	modified:   MANIFEST.in
	modified:   README.rst
	deleted:    conda-recipe/bld.bat
	deleted:    conda-recipe/build.sh
	deleted:    conda-recipe/conda_build_config.yaml
	deleted:    conda-recipe/meta.yaml
	deleted:    conda-recipe/run_test.py
	deleted:    devutils/makesdist
	modified:   pyproject.toml
	deleted:    setup.py
	modified:   src/diffpy/__init__.py
	modified:   src/diffpy/srfit/__init__.py
	modified:   src/diffpy/srfit/version.py
```

### CODE REVIEW

**Review by sbillinge — COMMENTED** [review]
are we cookiecutting with a cookiecutter that isn't ready here?  I don't see @tieqiong's work on the workflow stubs.

Let's finalize the cookiecutter before we do this.

**Comment by bobleesj** [comment]
sounds good, in the meantime, I will try to separate the tests folder from src.

**Comment by Tieqiong** [comment]
I think the reason why the workflow modification is not shown is because those changes are in `central-park` branch, while I think @bobleesj is using main.
I'll try to push changes for the versioning (see diffpy/diffpy.utils#99) and possibly some changes for cookiecutter automation today. I'll notice @bobleesj when things are ready.

**Comment by sbillinge** [comment]
Please advise what to do here.  I am guessing close this and start over?

**Comment by bobleesj** [comment]
@sbillinge  Okay, closing this and will start over with the latest cookiecutter repo once all tested.

**Pull request closed without merging**
